name: appflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # ✅ 1. Thêm package flutter_localizations
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.11
  dio: ^5.5.0
  path: ^1.9.0
  pretty_dio_logger: ^1.3.1
  motion_toast: ^2.7.5
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  intl: ^0.20.2 # Package intl đã có, rất tốt!
  share_plus: ^12.0.0
  image_picker: ^1.2.0
  provider: ^6.1.2 # ✅ 2. Thêm provider để quản lý state
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  connectivity_plus: ^5.0.2
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # ✅ 3. Bật tính năng generate code cho localization
  generate: true
  uses-material-design: true
  assets:
    - assets/
